# Generated by Django 5.1.6 on 2025-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcredential',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
