# Generated by Django 5.1.6 on 2025-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authcredential_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcredential',
            name='account_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
